version: 0.2
env:
  variables:
    CACHE_CONTROL: "86400"
    S3_BUCKET: "p3-client"
    BUILD_ENV: "prod"
    APP_NAME: "p3-angular"   
phases:
  install:
    runtime-versions:
      nodejs: 16.x
    commands:
      - echo install process started
      - npm install && npm install -g @angular/cli
  build:
    commands:
      - echo build process started now
      - ng build --configuration=production
artifacts:
  files:
    - '**/*'     
  base-directory: 'dist'
  discard-paths: yes